### ISSUE TITLE
Let PayPal know this is a CiviCRM site

### ISSUE THREAD

**Issue by JoeMurray** [agileware/cf-paypal-express#1]
Include support for letting PayPal know a site running this code this is a CiviCRM site so they can compensate CiviCRM LLC.

@agileware-justin I noticed your 🤢  in response to learning about this. Would like us to submit a PR for this so you don't have to? Would you merge it if we did?

**Comment by agileware-justin** [comment]
This is being actively discussed, https://lab.civicrm.org/dev/financial/-/issues/167
